# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  welcome: circleci/welcome-orb@0.4.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: |
          # echo Hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: |
          # echo World
  naming:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Setup custom environment variables"
          command: echo 'export MY_NAME="MICHAEL MEKULEYI"' >> $BASH_ENV
      - run: # print the name of the branch we're on
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "What was my custom environment variable?"
          command: echo ${MY_NAME}

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  helloWorld:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
  
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
  
